/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CanvasBackground, CanvasSidebarStartUpdateEventDetail } from "./components/canvas/canvas-utils";
import { CarouselAlignControls, CarouselAlignHeader, CarouselAriaAttribute, CarouselHeadingSize, CarouselInternationalization, CarouselSlidesPerPage, CarouselUpdateEventDetail, CarouselWidth } from "./components/carousel/carousel-utils";
import { BreakpointCustomizable, SelectedAriaAttributes } from "./types";
import { DrilldownAriaAttribute, DrilldownDismissEventDetail, DrilldownUpdateEventDetail } from "./components/drilldown/drilldown/drilldown-utils";
import { DrilldownLinkAriaAttribute, DrilldownLinkTarget } from "./components/drilldown/drilldown-link/drilldown-link-utils";
import { SheetAriaAttribute, SheetBackground, SheetDismissEventDetail, SheetMotionHiddenEndEventDetail, SheetMotionVisibleEndEventDetail } from "./components/sheet/sheet-utils";
export { CanvasBackground, CanvasSidebarStartUpdateEventDetail } from "./components/canvas/canvas-utils";
export { CarouselAlignControls, CarouselAlignHeader, CarouselAriaAttribute, CarouselHeadingSize, CarouselInternationalization, CarouselSlidesPerPage, CarouselUpdateEventDetail, CarouselWidth } from "./components/carousel/carousel-utils";
export { BreakpointCustomizable, SelectedAriaAttributes } from "./types";
export { DrilldownAriaAttribute, DrilldownDismissEventDetail, DrilldownUpdateEventDetail } from "./components/drilldown/drilldown/drilldown-utils";
export { DrilldownLinkAriaAttribute, DrilldownLinkTarget } from "./components/drilldown/drilldown-link/drilldown-link-utils";
export { SheetAriaAttribute, SheetBackground, SheetDismissEventDetail, SheetMotionHiddenEndEventDetail, SheetMotionVisibleEndEventDetail } from "./components/sheet/sheet-utils";
export namespace Components {
    /**
     * @experimental 
     */
    interface PCanvas {
        /**
          * Sets the background color of the main content area and automatically applies a matching color to the sidebar.
          * @default 'canvas'
         */
        "background"?: CanvasBackground;
        /**
          * Controls whether the utility sidebar on the end side (right in LTR) is open or collapsed.
          * @default false
         */
        "sidebarEndOpen"?: boolean;
        /**
          * Controls whether the navigation sidebar on the start side (left in LTR) is open or collapsed.
          * @default false
         */
        "sidebarStartOpen"?: boolean;
    }
    /**
     * @controlled { "props": ["activeSlideIndex"], "event": "update", "isInternallyMutated": true }
     */
    interface PCarousel {
        /**
          * Sets the zero-based index of the currently visible slide. Update this to navigate programmatically.
          * @default 0
         */
        "activeSlideIndex"?: number;
        /**
          * Controls the alignment of custom slotted controls within the header area.
          * @default 'auto'
         */
        "alignControls"?: CarouselAlignControls;
        /**
          * Controls the horizontal alignment of the heading and description.
          * @default 'start'
         */
        "alignHeader"?: CarouselAlignHeader;
        /**
          * Sets ARIA attributes on the carousel region element for improved accessibility.
         */
        "aria"?: SelectedAriaAttributes<CarouselAriaAttribute>;
        /**
          * Sets the description text displayed below the heading for additional context.
         */
        "description"?: string;
        /**
          * When enabled, each slide is individually focusable and the carousel navigates one slide at a time instead of one page.
          * @default false
         */
        "focusOnCenterSlide"?: boolean;
        /**
          * Shows a gradient fade at the start and end edges to visually indicate more slides beyond the viewport.
          * @default false
         */
        "gradient"?: boolean;
        /**
          * Sets the heading text displayed above the carousel. Also used as the accessible label when no `aria` prop is set.
         */
        "heading"?: string;
        /**
          * Sets the font size of the carousel heading.
          * @default 'x-large'
         */
        "headingSize"?: CarouselHeadingSize;
        /**
          * Overrides the default label strings used for the previous, next, and page indicators — useful for localization.
         */
        "intl"?: CarouselInternationalization;
        /**
          * Shows pagination dot indicators below the carousel. Supports responsive breakpoint values.
          * @default false
         */
        "pagination"?: BreakpointCustomizable<boolean>;
        /**
          * Enables infinite looping — navigating past the last slide wraps back to the first, and vice versa.
          * @default false
         */
        "rewind"?: boolean;
        /**
          * Sets the `href` of an in-page skip link that lets keyboard users jump past the carousel slides.
         */
        "skipLinkTarget"?: string;
        /**
          * Sets how many slides are visible at once. Use `auto` to control each slide's width via CSS. Supports responsive breakpoint values.
          * @default 1
         */
        "slidesPerPage"?: BreakpointCustomizable<CarouselSlidesPerPage>;
        /**
          * Removes whitespace before the first and after the last slide when `focusOnCenterSlide` is enabled.
          * @default false
         */
        "trimSpace"?: boolean;
        /**
          * Sets the maximum width and outer spacing of the carousel, aligned to PDS grid widths.
          * @default 'basic'
         */
        "width"?: CarouselWidth;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     * @controlled {"props": ["activeIdentifier"], "event": "update"}
     * @experimental 
     */
    interface PDrilldown {
        /**
          * Sets which `p-drilldown-item` (by `identifier`) is currently expanded to show its sub-navigation level.
         */
        "activeIdentifier"?: string | undefined;
        /**
          * Sets ARIA attributes on the drilldown dialog element for improved screen reader accessibility.
         */
        "aria"?: SelectedAriaAttributes<DrilldownAriaAttribute>;
        /**
          * Controls whether the drilldown navigation panel is visible.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * @experimental 
     */
    interface PDrilldownItem {
        /**
          * Private property set by the component itself.
          * @default false
         */
        "cascade"?: boolean;
        /**
          * Sets the unique identifier matched against the drilldown's `activeIdentifier` to determine if this item is shown.
         */
        "identifier": string;
        /**
          * Sets the text used for the back button, sticky header, and cascade button that navigates into this navigation level.
         */
        "label"?: string;
        /**
          * Private property set by the component itself.
          * @default false
         */
        "primary"?: boolean;
        /**
          * Private property set by the component itself.
          * @default false
         */
        "secondary"?: boolean;
    }
    /**
     * @experimental 
     */
    interface PDrilldownLink {
        /**
          * Visually marks the link as the currently active navigation item, e.g. the current page.
          * @default false
         */
        "active"?: boolean;
        /**
          * Sets ARIA attributes on the link for improved accessibility. Only applies when `href` is set.
         */
        "aria"?: SelectedAriaAttributes<DrilldownLinkAriaAttribute>;
        /**
          * Sets the native `download` attribute to trigger a file download. Only applies when `href` is set.
         */
        "download"?: string;
        /**
          * When set, the component renders as an anchor navigating to this URL. Otherwise, provide a slotted anchor element.
         */
        "href"?: string;
        /**
          * Sets the `rel` attribute on the link element (e.g. `noopener`). Only applies when `href` is set.
         */
        "rel"?: string;
        /**
          * Specifies where to open the linked URL (e.g. `_self`, `_blank`). Only applies when `href` is set.
          * @default '_self'
         */
        "target"?: DrilldownLinkTarget;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface PSheet {
        /**
          * Sets ARIA attributes on the sheet dialog element for improved accessibility when the default `aria-label` is insufficient.
         */
        "aria"?: SelectedAriaAttributes<SheetAriaAttribute>;
        /**
          * Sets the background color of the sheet panel (`canvas` or `surface`).
          * @default 'canvas'
         */
        "background"?: SheetBackground;
        /**
          * When enabled, clicking the backdrop will not close the sheet.
          * @default false
         */
        "disableBackdropClick"?: boolean;
        /**
          * Shows a dismiss button in the sheet header so users can manually close it.
          * @default true
         */
        "dismissButton"?: boolean;
        /**
          * Controls whether the sheet panel slides in from the bottom and is visible to the user.
          * @default false
         */
        "open": boolean;
    }
}
export interface PCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPCanvasElement;
}
export interface PCarouselCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPCarouselElement;
}
export interface PDrilldownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPDrilldownElement;
}
export interface PSheetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPSheetElement;
}
declare global {
    interface HTMLPCanvasElementEventMap {
        "sidebarStartUpdate": CanvasSidebarStartUpdateEventDetail;
        "sidebarEndDismiss": void;
    }
    /**
     * @experimental 
     */
    interface HTMLPCanvasElement extends Components.PCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPCanvasElementEventMap>(type: K, listener: (this: HTMLPCanvasElement, ev: PCanvasCustomEvent<HTMLPCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPCanvasElementEventMap>(type: K, listener: (this: HTMLPCanvasElement, ev: PCanvasCustomEvent<HTMLPCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPCanvasElement: {
        prototype: HTMLPCanvasElement;
        new (): HTMLPCanvasElement;
    };
    interface HTMLPCarouselElementEventMap {
        "update": CarouselUpdateEventDetail;
    }
    /**
     * @controlled { "props": ["activeSlideIndex"], "event": "update", "isInternallyMutated": true }
     */
    interface HTMLPCarouselElement extends Components.PCarousel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPCarouselElementEventMap>(type: K, listener: (this: HTMLPCarouselElement, ev: PCarouselCustomEvent<HTMLPCarouselElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPCarouselElementEventMap>(type: K, listener: (this: HTMLPCarouselElement, ev: PCarouselCustomEvent<HTMLPCarouselElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPCarouselElement: {
        prototype: HTMLPCarouselElement;
        new (): HTMLPCarouselElement;
    };
    interface HTMLPDrilldownElementEventMap {
        "dismiss": DrilldownDismissEventDetail;
        "update": DrilldownUpdateEventDetail;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     * @controlled {"props": ["activeIdentifier"], "event": "update"}
     * @experimental 
     */
    interface HTMLPDrilldownElement extends Components.PDrilldown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPDrilldownElementEventMap>(type: K, listener: (this: HTMLPDrilldownElement, ev: PDrilldownCustomEvent<HTMLPDrilldownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPDrilldownElementEventMap>(type: K, listener: (this: HTMLPDrilldownElement, ev: PDrilldownCustomEvent<HTMLPDrilldownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPDrilldownElement: {
        prototype: HTMLPDrilldownElement;
        new (): HTMLPDrilldownElement;
    };
    /**
     * @experimental 
     */
    interface HTMLPDrilldownItemElement extends Components.PDrilldownItem, HTMLStencilElement {
    }
    var HTMLPDrilldownItemElement: {
        prototype: HTMLPDrilldownItemElement;
        new (): HTMLPDrilldownItemElement;
    };
    /**
     * @experimental 
     */
    interface HTMLPDrilldownLinkElement extends Components.PDrilldownLink, HTMLStencilElement {
    }
    var HTMLPDrilldownLinkElement: {
        prototype: HTMLPDrilldownLinkElement;
        new (): HTMLPDrilldownLinkElement;
    };
    interface HTMLPSheetElementEventMap {
        "dismiss": SheetDismissEventDetail;
        "motionVisibleEnd": SheetMotionVisibleEndEventDetail;
        "motionHiddenEnd": SheetMotionHiddenEndEventDetail;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface HTMLPSheetElement extends Components.PSheet, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPSheetElementEventMap>(type: K, listener: (this: HTMLPSheetElement, ev: PSheetCustomEvent<HTMLPSheetElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPSheetElementEventMap>(type: K, listener: (this: HTMLPSheetElement, ev: PSheetCustomEvent<HTMLPSheetElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPSheetElement: {
        prototype: HTMLPSheetElement;
        new (): HTMLPSheetElement;
    };
    interface HTMLElementTagNameMap {
        "p-canvas": HTMLPCanvasElement;
        "p-carousel": HTMLPCarouselElement;
        "p-drilldown": HTMLPDrilldownElement;
        "p-drilldown-item": HTMLPDrilldownItemElement;
        "p-drilldown-link": HTMLPDrilldownLinkElement;
        "p-sheet": HTMLPSheetElement;
    }
}
declare namespace LocalJSX {
    /**
     * @experimental 
     */
    interface PCanvas {
        /**
          * Sets the background color of the main content area and automatically applies a matching color to the sidebar.
          * @default 'canvas'
         */
        "background"?: CanvasBackground;
        /**
          * Emitted when the user dismisses the end sidebar via the close button.
         */
        "onSidebarEndDismiss"?: (event: PCanvasCustomEvent<void>) => void;
        /**
          * Emitted when the user toggles the start sidebar, with the new open state in the event detail.
         */
        "onSidebarStartUpdate"?: (event: PCanvasCustomEvent<CanvasSidebarStartUpdateEventDetail>) => void;
        /**
          * Controls whether the utility sidebar on the end side (right in LTR) is open or collapsed.
          * @default false
         */
        "sidebarEndOpen"?: boolean;
        /**
          * Controls whether the navigation sidebar on the start side (left in LTR) is open or collapsed.
          * @default false
         */
        "sidebarStartOpen"?: boolean;
    }
    /**
     * @controlled { "props": ["activeSlideIndex"], "event": "update", "isInternallyMutated": true }
     */
    interface PCarousel {
        /**
          * Sets the zero-based index of the currently visible slide. Update this to navigate programmatically.
          * @default 0
         */
        "activeSlideIndex"?: number;
        /**
          * Controls the alignment of custom slotted controls within the header area.
          * @default 'auto'
         */
        "alignControls"?: CarouselAlignControls;
        /**
          * Controls the horizontal alignment of the heading and description.
          * @default 'start'
         */
        "alignHeader"?: CarouselAlignHeader;
        /**
          * Sets ARIA attributes on the carousel region element for improved accessibility.
         */
        "aria"?: SelectedAriaAttributes<CarouselAriaAttribute>;
        /**
          * Sets the description text displayed below the heading for additional context.
         */
        "description"?: string;
        /**
          * When enabled, each slide is individually focusable and the carousel navigates one slide at a time instead of one page.
          * @default false
         */
        "focusOnCenterSlide"?: boolean;
        /**
          * Shows a gradient fade at the start and end edges to visually indicate more slides beyond the viewport.
          * @default false
         */
        "gradient"?: boolean;
        /**
          * Sets the heading text displayed above the carousel. Also used as the accessible label when no `aria` prop is set.
         */
        "heading"?: string;
        /**
          * Sets the font size of the carousel heading.
          * @default 'x-large'
         */
        "headingSize"?: CarouselHeadingSize;
        /**
          * Overrides the default label strings used for the previous, next, and page indicators — useful for localization.
         */
        "intl"?: CarouselInternationalization;
        /**
          * Emitted when the carousel navigates to a new slide, with the active and previous slide indexes in the event detail.
         */
        "onUpdate"?: (event: PCarouselCustomEvent<CarouselUpdateEventDetail>) => void;
        /**
          * Shows pagination dot indicators below the carousel. Supports responsive breakpoint values.
          * @default false
         */
        "pagination"?: BreakpointCustomizable<boolean>;
        /**
          * Enables infinite looping — navigating past the last slide wraps back to the first, and vice versa.
          * @default false
         */
        "rewind"?: boolean;
        /**
          * Sets the `href` of an in-page skip link that lets keyboard users jump past the carousel slides.
         */
        "skipLinkTarget"?: string;
        /**
          * Sets how many slides are visible at once. Use `auto` to control each slide's width via CSS. Supports responsive breakpoint values.
          * @default 1
         */
        "slidesPerPage"?: BreakpointCustomizable<CarouselSlidesPerPage>;
        /**
          * Removes whitespace before the first and after the last slide when `focusOnCenterSlide` is enabled.
          * @default false
         */
        "trimSpace"?: boolean;
        /**
          * Sets the maximum width and outer spacing of the carousel, aligned to PDS grid widths.
          * @default 'basic'
         */
        "width"?: CarouselWidth;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     * @controlled {"props": ["activeIdentifier"], "event": "update"}
     * @experimental 
     */
    interface PDrilldown {
        /**
          * Sets which `p-drilldown-item` (by `identifier`) is currently expanded to show its sub-navigation level.
         */
        "activeIdentifier"?: string | undefined;
        /**
          * Sets ARIA attributes on the drilldown dialog element for improved screen reader accessibility.
         */
        "aria"?: SelectedAriaAttributes<DrilldownAriaAttribute>;
        /**
          * Emitted when the user closes the drilldown via the dismiss button, backdrop click, or Escape key. The event detail identifies which of the three was used.
         */
        "onDismiss"?: (event: PDrilldownCustomEvent<DrilldownDismissEventDetail>) => void;
        /**
          * Emitted when the active navigation level changes, with the new `activeIdentifier` in the event detail.
         */
        "onUpdate"?: (event: PDrilldownCustomEvent<DrilldownUpdateEventDetail>) => void;
        /**
          * Controls whether the drilldown navigation panel is visible.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * @experimental 
     */
    interface PDrilldownItem {
        /**
          * Private property set by the component itself.
          * @default false
         */
        "cascade"?: boolean;
        /**
          * Sets the unique identifier matched against the drilldown's `activeIdentifier` to determine if this item is shown.
         */
        "identifier"?: string;
        /**
          * Sets the text used for the back button, sticky header, and cascade button that navigates into this navigation level.
         */
        "label"?: string;
        /**
          * Private property set by the component itself.
          * @default false
         */
        "primary"?: boolean;
        /**
          * Private property set by the component itself.
          * @default false
         */
        "secondary"?: boolean;
    }
    /**
     * @experimental 
     */
    interface PDrilldownLink {
        /**
          * Visually marks the link as the currently active navigation item, e.g. the current page.
          * @default false
         */
        "active"?: boolean;
        /**
          * Sets ARIA attributes on the link for improved accessibility. Only applies when `href` is set.
         */
        "aria"?: SelectedAriaAttributes<DrilldownLinkAriaAttribute>;
        /**
          * Sets the native `download` attribute to trigger a file download. Only applies when `href` is set.
         */
        "download"?: string;
        /**
          * When set, the component renders as an anchor navigating to this URL. Otherwise, provide a slotted anchor element.
         */
        "href"?: string;
        /**
          * Sets the `rel` attribute on the link element (e.g. `noopener`). Only applies when `href` is set.
         */
        "rel"?: string;
        /**
          * Specifies where to open the linked URL (e.g. `_self`, `_blank`). Only applies when `href` is set.
          * @default '_self'
         */
        "target"?: DrilldownLinkTarget;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface PSheet {
        /**
          * Sets ARIA attributes on the sheet dialog element for improved accessibility when the default `aria-label` is insufficient.
         */
        "aria"?: SelectedAriaAttributes<SheetAriaAttribute>;
        /**
          * Sets the background color of the sheet panel (`canvas` or `surface`).
          * @default 'canvas'
         */
        "background"?: SheetBackground;
        /**
          * When enabled, clicking the backdrop will not close the sheet.
          * @default false
         */
        "disableBackdropClick"?: boolean;
        /**
          * Shows a dismiss button in the sheet header so users can manually close it.
          * @default true
         */
        "dismissButton"?: boolean;
        /**
          * Emitted when the user closes the sheet via the dismiss button, backdrop click, or Escape key. The event detail identifies which of the three was used.
         */
        "onDismiss"?: (event: PSheetCustomEvent<SheetDismissEventDetail>) => void;
        /**
          * Emitted after the sheet's close transition has fully completed and the panel is hidden.
         */
        "onMotionHiddenEnd"?: (event: PSheetCustomEvent<SheetMotionHiddenEndEventDetail>) => void;
        /**
          * Emitted after the sheet's open transition has fully completed and the panel is visible.
         */
        "onMotionVisibleEnd"?: (event: PSheetCustomEvent<SheetMotionVisibleEndEventDetail>) => void;
        /**
          * Controls whether the sheet panel slides in from the bottom and is visible to the user.
          * @default false
         */
        "open"?: boolean;
    }

    interface PCanvasAttributes {
        "sidebarStartOpen": boolean;
        "sidebarEndOpen": boolean;
        "background": CanvasBackground;
    }
    interface PCarouselAttributes {
        "heading": string;
        "headingSize": CarouselHeadingSize;
        "description": string;
        "alignHeader": CarouselAlignHeader;
        "alignControls": CarouselAlignControls;
        "rewind": boolean;
        "width": CarouselWidth;
        "slidesPerPage": string;
        "pagination": string;
        "aria": SelectedAriaAttributes<CarouselAriaAttribute>;
        "intl": CarouselInternationalization;
        "activeSlideIndex": number;
        "skipLinkTarget": string;
        "focusOnCenterSlide": boolean;
        "gradient": boolean;
        "trimSpace": boolean;
    }
    interface PDrilldownAttributes {
        "open": boolean;
        "activeIdentifier": string | undefined;
        "aria": SelectedAriaAttributes<DrilldownAriaAttribute>;
    }
    interface PDrilldownItemAttributes {
        "label": string;
        "identifier": string;
        "primary": boolean;
        "secondary": boolean;
        "cascade": boolean;
    }
    interface PDrilldownLinkAttributes {
        "href": string;
        "active": boolean;
        "target": DrilldownLinkTarget;
        "download": string;
        "rel": string;
        "aria": SelectedAriaAttributes<DrilldownLinkAriaAttribute>;
    }
    interface PSheetAttributes {
        "open": boolean;
        "dismissButton": boolean;
        "disableBackdropClick": boolean;
        "background": SheetBackground;
        "aria": SelectedAriaAttributes<SheetAriaAttribute>;
    }

    interface IntrinsicElements {
        "p-canvas": Omit<PCanvas, keyof PCanvasAttributes> & { [K in keyof PCanvas & keyof PCanvasAttributes]?: PCanvas[K] } & { [K in keyof PCanvas & keyof PCanvasAttributes as `attr:${K}`]?: PCanvasAttributes[K] } & { [K in keyof PCanvas & keyof PCanvasAttributes as `prop:${K}`]?: PCanvas[K] };
        "p-carousel": Omit<PCarousel, keyof PCarouselAttributes> & { [K in keyof PCarousel & keyof PCarouselAttributes]?: PCarousel[K] } & { [K in keyof PCarousel & keyof PCarouselAttributes as `attr:${K}`]?: PCarouselAttributes[K] } & { [K in keyof PCarousel & keyof PCarouselAttributes as `prop:${K}`]?: PCarousel[K] };
        "p-drilldown": Omit<PDrilldown, keyof PDrilldownAttributes> & { [K in keyof PDrilldown & keyof PDrilldownAttributes]?: PDrilldown[K] } & { [K in keyof PDrilldown & keyof PDrilldownAttributes as `attr:${K}`]?: PDrilldownAttributes[K] } & { [K in keyof PDrilldown & keyof PDrilldownAttributes as `prop:${K}`]?: PDrilldown[K] };
        "p-drilldown-item": Omit<PDrilldownItem, keyof PDrilldownItemAttributes> & { [K in keyof PDrilldownItem & keyof PDrilldownItemAttributes]?: PDrilldownItem[K] } & { [K in keyof PDrilldownItem & keyof PDrilldownItemAttributes as `attr:${K}`]?: PDrilldownItemAttributes[K] } & { [K in keyof PDrilldownItem & keyof PDrilldownItemAttributes as `prop:${K}`]?: PDrilldownItem[K] };
        "p-drilldown-link": Omit<PDrilldownLink, keyof PDrilldownLinkAttributes> & { [K in keyof PDrilldownLink & keyof PDrilldownLinkAttributes]?: PDrilldownLink[K] } & { [K in keyof PDrilldownLink & keyof PDrilldownLinkAttributes as `attr:${K}`]?: PDrilldownLinkAttributes[K] } & { [K in keyof PDrilldownLink & keyof PDrilldownLinkAttributes as `prop:${K}`]?: PDrilldownLink[K] };
        "p-sheet": Omit<PSheet, keyof PSheetAttributes> & { [K in keyof PSheet & keyof PSheetAttributes]?: PSheet[K] } & { [K in keyof PSheet & keyof PSheetAttributes as `attr:${K}`]?: PSheetAttributes[K] } & { [K in keyof PSheet & keyof PSheetAttributes as `prop:${K}`]?: PSheet[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @experimental 
             */
            "p-canvas": LocalJSX.IntrinsicElements["p-canvas"] & JSXBase.HTMLAttributes<HTMLPCanvasElement>;
            /**
             * @controlled { "props": ["activeSlideIndex"], "event": "update", "isInternallyMutated": true }
             */
            "p-carousel": LocalJSX.IntrinsicElements["p-carousel"] & JSXBase.HTMLAttributes<HTMLPCarouselElement>;
            /**
             * @controlled {"props": ["open"], "event": "dismiss"}
             * @controlled {"props": ["activeIdentifier"], "event": "update"}
             * @experimental 
             */
            "p-drilldown": LocalJSX.IntrinsicElements["p-drilldown"] & JSXBase.HTMLAttributes<HTMLPDrilldownElement>;
            /**
             * @experimental 
             */
            "p-drilldown-item": LocalJSX.IntrinsicElements["p-drilldown-item"] & JSXBase.HTMLAttributes<HTMLPDrilldownItemElement>;
            /**
             * @experimental 
             */
            "p-drilldown-link": LocalJSX.IntrinsicElements["p-drilldown-link"] & JSXBase.HTMLAttributes<HTMLPDrilldownLinkElement>;
            /**
             * @controlled {"props": ["open"], "event": "dismiss"}
             */
            "p-sheet": LocalJSX.IntrinsicElements["p-sheet"] & JSXBase.HTMLAttributes<HTMLPSheetElement>;
        }
    }
}
