/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CanvasBackground, CanvasSidebarStartUpdateEventDetail } from "./components/canvas/canvas-utils";
import { CarouselAlignControls, CarouselAlignHeader, CarouselAriaAttribute, CarouselHeadingSize, CarouselInternationalization, CarouselSlidesPerPage, CarouselUpdateEventDetail, CarouselWidth } from "./components/carousel/carousel-utils";
import { BreakpointCustomizable, SelectedAriaAttributes } from "./types";
import { DrilldownAriaAttribute, DrilldownDismissEventDetail, DrilldownUpdateEventDetail } from "./components/drilldown/drilldown/drilldown-utils";
import { DrilldownLinkAriaAttribute, DrilldownLinkTarget } from "./components/drilldown/drilldown-link/drilldown-link-utils";
import { FlyoutAriaAttribute, FlyoutBackdrop, FlyoutBackground, FlyoutDismissEventDetail, FlyoutFooterBehavior, FlyoutMotionHiddenEndEventDetail, FlyoutMotionVisibleEndEventDetail, FlyoutPosition } from "./components/flyout/flyout-utils";
import { ModalAriaAttribute, ModalBackdrop, ModalBackground, ModalDismissEventDetail, ModalMotionHiddenEndEventDetail, ModalMotionVisibleEndEventDetail } from "./components/modal/modal-utils";
import { SheetAriaAttribute, SheetBackground, SheetDismissEventDetail, SheetMotionHiddenEndEventDetail, SheetMotionVisibleEndEventDetail } from "./components/sheet/sheet-utils";
import { TableHeadCellSort } from "./components/table/table/table-utils";
import { ToastMessage } from "./components/toast/toast/toast-manager";
import { ToastState } from "./components/toast/toast/toast-utils";
export { CanvasBackground, CanvasSidebarStartUpdateEventDetail } from "./components/canvas/canvas-utils";
export { CarouselAlignControls, CarouselAlignHeader, CarouselAriaAttribute, CarouselHeadingSize, CarouselInternationalization, CarouselSlidesPerPage, CarouselUpdateEventDetail, CarouselWidth } from "./components/carousel/carousel-utils";
export { BreakpointCustomizable, SelectedAriaAttributes } from "./types";
export { DrilldownAriaAttribute, DrilldownDismissEventDetail, DrilldownUpdateEventDetail } from "./components/drilldown/drilldown/drilldown-utils";
export { DrilldownLinkAriaAttribute, DrilldownLinkTarget } from "./components/drilldown/drilldown-link/drilldown-link-utils";
export { FlyoutAriaAttribute, FlyoutBackdrop, FlyoutBackground, FlyoutDismissEventDetail, FlyoutFooterBehavior, FlyoutMotionHiddenEndEventDetail, FlyoutMotionVisibleEndEventDetail, FlyoutPosition } from "./components/flyout/flyout-utils";
export { ModalAriaAttribute, ModalBackdrop, ModalBackground, ModalDismissEventDetail, ModalMotionHiddenEndEventDetail, ModalMotionVisibleEndEventDetail } from "./components/modal/modal-utils";
export { SheetAriaAttribute, SheetBackground, SheetDismissEventDetail, SheetMotionHiddenEndEventDetail, SheetMotionVisibleEndEventDetail } from "./components/sheet/sheet-utils";
export { TableHeadCellSort } from "./components/table/table/table-utils";
export { ToastMessage } from "./components/toast/toast/toast-manager";
export { ToastState } from "./components/toast/toast/toast-utils";
export namespace Components {
    /**
     * @experimental 
     */
    interface PCanvas {
        /**
          * Sets the background color of the main content area and automatically applies a matching color to the sidebar.
          * @default 'canvas'
         */
        "background"?: CanvasBackground;
        /**
          * Controls whether the utility sidebar on the end side (right in LTR) is open or collapsed.
          * @default false
         */
        "sidebarEndOpen"?: boolean;
        /**
          * Controls whether the navigation sidebar on the start side (left in LTR) is open or collapsed.
          * @default false
         */
        "sidebarStartOpen"?: boolean;
    }
    /**
     * @controlled { "props": ["activeSlideIndex"], "event": "update", "isInternallyMutated": true }
     */
    interface PCarousel {
        /**
          * Sets the zero-based index of the currently visible slide. Update this to navigate programmatically.
          * @default 0
         */
        "activeSlideIndex"?: number;
        /**
          * Controls the alignment of custom slotted controls within the header area.
          * @default 'auto'
         */
        "alignControls"?: CarouselAlignControls;
        /**
          * Controls the horizontal alignment of the heading and description.
          * @default 'start'
         */
        "alignHeader"?: CarouselAlignHeader;
        /**
          * Sets ARIA attributes on the carousel region element for improved accessibility.
         */
        "aria"?: SelectedAriaAttributes<CarouselAriaAttribute>;
        /**
          * Sets the description text displayed below the heading for additional context.
         */
        "description"?: string;
        /**
          * When enabled, each slide is individually focusable and the carousel navigates one slide at a time instead of one page.
          * @default false
         */
        "focusOnCenterSlide"?: boolean;
        /**
          * Shows a gradient fade at the start and end edges to visually indicate more slides beyond the viewport.
          * @default false
         */
        "gradient"?: boolean;
        /**
          * Sets the heading text displayed above the carousel. Also used as the accessible label when no `aria` prop is set.
         */
        "heading"?: string;
        /**
          * Sets the font size of the carousel heading.
          * @default 'x-large'
         */
        "headingSize"?: CarouselHeadingSize;
        /**
          * Overrides the default label strings used for the previous, next, and page indicators — useful for localization.
         */
        "intl"?: CarouselInternationalization;
        /**
          * Shows pagination dot indicators below the carousel. Supports responsive breakpoint values.
          * @default false
         */
        "pagination"?: BreakpointCustomizable<boolean>;
        /**
          * Enables infinite looping — navigating past the last slide wraps back to the first, and vice versa.
          * @default false
         */
        "rewind"?: boolean;
        /**
          * Sets the `href` of an in-page skip link that lets keyboard users jump past the carousel slides.
         */
        "skipLinkTarget"?: string;
        /**
          * Sets how many slides are visible at once. Use `auto` to control each slide's width via CSS. Supports responsive breakpoint values.
          * @default 1
         */
        "slidesPerPage"?: BreakpointCustomizable<CarouselSlidesPerPage>;
        /**
          * Removes whitespace before the first and after the last slide when `focusOnCenterSlide` is enabled.
          * @default false
         */
        "trimSpace"?: boolean;
        /**
          * Sets the maximum width and outer spacing of the carousel, aligned to PDS grid widths.
          * @default 'basic'
         */
        "width"?: CarouselWidth;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     * @controlled {"props": ["activeIdentifier"], "event": "update"}
     * @experimental 
     */
    interface PDrilldown {
        /**
          * Sets which `p-drilldown-item` (by `identifier`) is currently expanded to show its sub-navigation level.
         */
        "activeIdentifier"?: string | undefined;
        /**
          * Sets ARIA attributes on the drilldown dialog element for improved screen reader accessibility.
         */
        "aria"?: SelectedAriaAttributes<DrilldownAriaAttribute>;
        /**
          * Controls whether the drilldown navigation panel is visible.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * @experimental 
     */
    interface PDrilldownItem {
        /**
          * Private property set by the component itself.
          * @default false
         */
        "cascade"?: boolean;
        /**
          * Sets the unique identifier matched against the drilldown's `activeIdentifier` to determine if this item is shown.
         */
        "identifier": string;
        /**
          * Sets the text used for the back button, sticky header, and cascade button that navigates into this navigation level.
         */
        "label"?: string;
        /**
          * Private property set by the component itself.
          * @default false
         */
        "primary"?: boolean;
        /**
          * Private property set by the component itself.
          * @default false
         */
        "secondary"?: boolean;
    }
    /**
     * @experimental 
     */
    interface PDrilldownLink {
        /**
          * Visually marks the link as the currently active navigation item, e.g. the current page.
          * @default false
         */
        "active"?: boolean;
        /**
          * Sets ARIA attributes on the link for improved accessibility. Only applies when `href` is set.
         */
        "aria"?: SelectedAriaAttributes<DrilldownLinkAriaAttribute>;
        /**
          * Sets the native `download` attribute to trigger a file download. Only applies when `href` is set.
         */
        "download"?: string;
        /**
          * When set, the component renders as an anchor navigating to this URL. Otherwise, provide a slotted anchor element.
         */
        "href"?: string;
        /**
          * Sets the `rel` attribute on the link element (e.g. `noopener`). Only applies when `href` is set.
         */
        "rel"?: string;
        /**
          * Specifies where to open the linked URL (e.g. `_self`, `_blank`). Only applies when `href` is set.
          * @default '_self'
         */
        "target"?: DrilldownLinkTarget;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface PFlyout {
        /**
          * Sets ARIA attributes on the flyout dialog element for improved screen reader accessibility.
         */
        "aria"?: SelectedAriaAttributes<FlyoutAriaAttribute>;
        /**
          * Sets the backdrop style. Use `blur` when background content is irrelevant; use `shading` when users still need visual context.
          * @default 'blur'
         */
        "backdrop"?: FlyoutBackdrop;
        /**
          * Sets the background color of the flyout panel (`canvas` or `surface`).
          * @default 'canvas'
         */
        "background"?: FlyoutBackground;
        /**
          * When enabled, clicking the backdrop will not close the flyout.
          * @default false
         */
        "disableBackdropClick"?: boolean;
        /**
          * Controls footer behavior. `fixed` keeps it anchored at the bottom; `sticky` pins it only when content overflows.
          * @default 'sticky'
         */
        "footerBehavior"?: FlyoutFooterBehavior;
        /**
          * If true the flyout stretches to the full viewport width with squared corners. Useful for smaller viewports where the flyout would otherwise fill the screen but still show rounded corners.
          * @default false
         */
        "fullscreen"?: BreakpointCustomizable<boolean>;
        /**
          * Controls whether the flyout panel is visible.
          * @default false
         */
        "open": boolean;
        /**
          * Sets the side the flyout slides in from — `start` for left or `end` for right in LTR layouts.
          * @default 'end'
         */
        "position"?: FlyoutPosition;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface PModal {
        /**
          * Sets ARIA attributes on the dialog element for improved accessibility when no visible heading is present.
         */
        "aria"?: SelectedAriaAttributes<ModalAriaAttribute>;
        /**
          * Sets the backdrop style. Use `blur` when the modal is opened by user interaction; use `shading` when opened automatically (e.g. Cookie Consent).
          * @default 'blur'
         */
        "backdrop"?: ModalBackdrop;
        /**
          * Sets the background color of the modal panel (`canvas` or `surface`).
          * @default 'canvas'
         */
        "background"?: ModalBackground;
        /**
          * When enabled, clicking the backdrop will not close the modal.
          * @default false
         */
        "disableBackdropClick"?: boolean;
        /**
          * Shows a dismiss button in the modal header so the user can manually close it.
          * @default true
         */
        "dismissButton"?: boolean;
        /**
          * Expands the modal to the full viewport size, intended for mobile use cases. Supports responsive breakpoint values.
          * @default false
         */
        "fullscreen"?: BreakpointCustomizable<boolean>;
        /**
          * Controls whether the modal dialog is visible.
          * @default false
         */
        "open": boolean;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface PSheet {
        /**
          * Sets ARIA attributes on the sheet dialog element for improved accessibility when the default `aria-label` is insufficient.
         */
        "aria"?: SelectedAriaAttributes<SheetAriaAttribute>;
        /**
          * Sets the background color of the sheet panel (`canvas` or `surface`).
          * @default 'canvas'
         */
        "background"?: SheetBackground;
        /**
          * When enabled, clicking the backdrop will not close the sheet.
          * @default false
         */
        "disableBackdropClick"?: boolean;
        /**
          * Shows a dismiss button in the sheet header so users can manually close it.
          * @default true
         */
        "dismissButton"?: boolean;
        /**
          * Controls whether the sheet panel slides in from the bottom and is visible to the user.
          * @default false
         */
        "open": boolean;
    }
    interface PTableBody {
    }
    interface PTableCell {
        /**
          * Allows slotted text to wrap onto multiple lines instead of being forced onto a single line.
          * @default false
         */
        "multiline"?: boolean;
    }
    interface PTableHeadCell {
        /**
          * Hides the visible column label while keeping it accessible to screen readers. Only applies when `sort` is not set.
          * @default false
         */
        "hideLabel"?: boolean;
        /**
          * Allows the column header text to wrap onto multiple lines instead of being truncated to a single line.
          * @default false
         */
        "multiline"?: boolean;
        /**
          * Configures sorting behavior for this column by providing an `id`, `active` state, and current `direction` (`asc` or `desc`).
         */
        "sort"?: TableHeadCellSort;
    }
    interface PTableRow {
    }
    interface PToast {
        "addMessage": (message: ToastMessage) => Promise<void>;
    }
    interface PToastItem {
        /**
          * Sets the visual and semantic state of the toast item, controlling its icon and color scheme (`info`, `warning`, `error`, `success`).
          * @default 'info'
         */
        "state"?: ToastState;
        /**
          * Sets the notification message text displayed inside the toast item to inform the user about the outcome of an action.
          * @default ''
         */
        "text"?: string;
    }
}
export interface PCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPCanvasElement;
}
export interface PCarouselCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPCarouselElement;
}
export interface PDrilldownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPDrilldownElement;
}
export interface PFlyoutCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPFlyoutElement;
}
export interface PModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPModalElement;
}
export interface PSheetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPSheetElement;
}
export interface PToastItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPToastItemElement;
}
declare global {
    interface HTMLPCanvasElementEventMap {
        "sidebarStartUpdate": CanvasSidebarStartUpdateEventDetail;
        "sidebarEndDismiss": void;
    }
    /**
     * @experimental 
     */
    interface HTMLPCanvasElement extends Components.PCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPCanvasElementEventMap>(type: K, listener: (this: HTMLPCanvasElement, ev: PCanvasCustomEvent<HTMLPCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPCanvasElementEventMap>(type: K, listener: (this: HTMLPCanvasElement, ev: PCanvasCustomEvent<HTMLPCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPCanvasElement: {
        prototype: HTMLPCanvasElement;
        new (): HTMLPCanvasElement;
    };
    interface HTMLPCarouselElementEventMap {
        "update": CarouselUpdateEventDetail;
    }
    /**
     * @controlled { "props": ["activeSlideIndex"], "event": "update", "isInternallyMutated": true }
     */
    interface HTMLPCarouselElement extends Components.PCarousel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPCarouselElementEventMap>(type: K, listener: (this: HTMLPCarouselElement, ev: PCarouselCustomEvent<HTMLPCarouselElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPCarouselElementEventMap>(type: K, listener: (this: HTMLPCarouselElement, ev: PCarouselCustomEvent<HTMLPCarouselElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPCarouselElement: {
        prototype: HTMLPCarouselElement;
        new (): HTMLPCarouselElement;
    };
    interface HTMLPDrilldownElementEventMap {
        "dismiss": DrilldownDismissEventDetail;
        "update": DrilldownUpdateEventDetail;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     * @controlled {"props": ["activeIdentifier"], "event": "update"}
     * @experimental 
     */
    interface HTMLPDrilldownElement extends Components.PDrilldown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPDrilldownElementEventMap>(type: K, listener: (this: HTMLPDrilldownElement, ev: PDrilldownCustomEvent<HTMLPDrilldownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPDrilldownElementEventMap>(type: K, listener: (this: HTMLPDrilldownElement, ev: PDrilldownCustomEvent<HTMLPDrilldownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPDrilldownElement: {
        prototype: HTMLPDrilldownElement;
        new (): HTMLPDrilldownElement;
    };
    /**
     * @experimental 
     */
    interface HTMLPDrilldownItemElement extends Components.PDrilldownItem, HTMLStencilElement {
    }
    var HTMLPDrilldownItemElement: {
        prototype: HTMLPDrilldownItemElement;
        new (): HTMLPDrilldownItemElement;
    };
    /**
     * @experimental 
     */
    interface HTMLPDrilldownLinkElement extends Components.PDrilldownLink, HTMLStencilElement {
    }
    var HTMLPDrilldownLinkElement: {
        prototype: HTMLPDrilldownLinkElement;
        new (): HTMLPDrilldownLinkElement;
    };
    interface HTMLPFlyoutElementEventMap {
        "dismiss": FlyoutDismissEventDetail;
        "motionVisibleEnd": FlyoutMotionVisibleEndEventDetail;
        "motionHiddenEnd": FlyoutMotionHiddenEndEventDetail;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface HTMLPFlyoutElement extends Components.PFlyout, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPFlyoutElementEventMap>(type: K, listener: (this: HTMLPFlyoutElement, ev: PFlyoutCustomEvent<HTMLPFlyoutElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPFlyoutElementEventMap>(type: K, listener: (this: HTMLPFlyoutElement, ev: PFlyoutCustomEvent<HTMLPFlyoutElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPFlyoutElement: {
        prototype: HTMLPFlyoutElement;
        new (): HTMLPFlyoutElement;
    };
    interface HTMLPModalElementEventMap {
        "dismiss": ModalDismissEventDetail;
        "motionVisibleEnd": ModalMotionVisibleEndEventDetail;
        "motionHiddenEnd": ModalMotionHiddenEndEventDetail;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface HTMLPModalElement extends Components.PModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPModalElementEventMap>(type: K, listener: (this: HTMLPModalElement, ev: PModalCustomEvent<HTMLPModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPModalElementEventMap>(type: K, listener: (this: HTMLPModalElement, ev: PModalCustomEvent<HTMLPModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPModalElement: {
        prototype: HTMLPModalElement;
        new (): HTMLPModalElement;
    };
    interface HTMLPSheetElementEventMap {
        "dismiss": SheetDismissEventDetail;
        "motionVisibleEnd": SheetMotionVisibleEndEventDetail;
        "motionHiddenEnd": SheetMotionHiddenEndEventDetail;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface HTMLPSheetElement extends Components.PSheet, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPSheetElementEventMap>(type: K, listener: (this: HTMLPSheetElement, ev: PSheetCustomEvent<HTMLPSheetElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPSheetElementEventMap>(type: K, listener: (this: HTMLPSheetElement, ev: PSheetCustomEvent<HTMLPSheetElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPSheetElement: {
        prototype: HTMLPSheetElement;
        new (): HTMLPSheetElement;
    };
    interface HTMLPTableBodyElement extends Components.PTableBody, HTMLStencilElement {
    }
    var HTMLPTableBodyElement: {
        prototype: HTMLPTableBodyElement;
        new (): HTMLPTableBodyElement;
    };
    interface HTMLPTableCellElement extends Components.PTableCell, HTMLStencilElement {
    }
    var HTMLPTableCellElement: {
        prototype: HTMLPTableCellElement;
        new (): HTMLPTableCellElement;
    };
    interface HTMLPTableHeadCellElement extends Components.PTableHeadCell, HTMLStencilElement {
    }
    var HTMLPTableHeadCellElement: {
        prototype: HTMLPTableHeadCellElement;
        new (): HTMLPTableHeadCellElement;
    };
    interface HTMLPTableRowElement extends Components.PTableRow, HTMLStencilElement {
    }
    var HTMLPTableRowElement: {
        prototype: HTMLPTableRowElement;
        new (): HTMLPTableRowElement;
    };
    interface HTMLPToastElement extends Components.PToast, HTMLStencilElement {
    }
    var HTMLPToastElement: {
        prototype: HTMLPToastElement;
        new (): HTMLPToastElement;
    };
    interface HTMLPToastItemElementEventMap {
        "dismiss": void;
    }
    interface HTMLPToastItemElement extends Components.PToastItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPToastItemElementEventMap>(type: K, listener: (this: HTMLPToastItemElement, ev: PToastItemCustomEvent<HTMLPToastItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPToastItemElementEventMap>(type: K, listener: (this: HTMLPToastItemElement, ev: PToastItemCustomEvent<HTMLPToastItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPToastItemElement: {
        prototype: HTMLPToastItemElement;
        new (): HTMLPToastItemElement;
    };
    interface HTMLElementTagNameMap {
        "p-canvas": HTMLPCanvasElement;
        "p-carousel": HTMLPCarouselElement;
        "p-drilldown": HTMLPDrilldownElement;
        "p-drilldown-item": HTMLPDrilldownItemElement;
        "p-drilldown-link": HTMLPDrilldownLinkElement;
        "p-flyout": HTMLPFlyoutElement;
        "p-modal": HTMLPModalElement;
        "p-sheet": HTMLPSheetElement;
        "p-table-body": HTMLPTableBodyElement;
        "p-table-cell": HTMLPTableCellElement;
        "p-table-head-cell": HTMLPTableHeadCellElement;
        "p-table-row": HTMLPTableRowElement;
        "p-toast": HTMLPToastElement;
        "p-toast-item": HTMLPToastItemElement;
    }
}
declare namespace LocalJSX {
    /**
     * @experimental 
     */
    interface PCanvas {
        /**
          * Sets the background color of the main content area and automatically applies a matching color to the sidebar.
          * @default 'canvas'
         */
        "background"?: CanvasBackground;
        /**
          * Emitted when the user dismisses the end sidebar via the close button.
         */
        "onSidebarEndDismiss"?: (event: PCanvasCustomEvent<void>) => void;
        /**
          * Emitted when the user toggles the start sidebar, with the new open state in the event detail.
         */
        "onSidebarStartUpdate"?: (event: PCanvasCustomEvent<CanvasSidebarStartUpdateEventDetail>) => void;
        /**
          * Controls whether the utility sidebar on the end side (right in LTR) is open or collapsed.
          * @default false
         */
        "sidebarEndOpen"?: boolean;
        /**
          * Controls whether the navigation sidebar on the start side (left in LTR) is open or collapsed.
          * @default false
         */
        "sidebarStartOpen"?: boolean;
    }
    /**
     * @controlled { "props": ["activeSlideIndex"], "event": "update", "isInternallyMutated": true }
     */
    interface PCarousel {
        /**
          * Sets the zero-based index of the currently visible slide. Update this to navigate programmatically.
          * @default 0
         */
        "activeSlideIndex"?: number;
        /**
          * Controls the alignment of custom slotted controls within the header area.
          * @default 'auto'
         */
        "alignControls"?: CarouselAlignControls;
        /**
          * Controls the horizontal alignment of the heading and description.
          * @default 'start'
         */
        "alignHeader"?: CarouselAlignHeader;
        /**
          * Sets ARIA attributes on the carousel region element for improved accessibility.
         */
        "aria"?: SelectedAriaAttributes<CarouselAriaAttribute>;
        /**
          * Sets the description text displayed below the heading for additional context.
         */
        "description"?: string;
        /**
          * When enabled, each slide is individually focusable and the carousel navigates one slide at a time instead of one page.
          * @default false
         */
        "focusOnCenterSlide"?: boolean;
        /**
          * Shows a gradient fade at the start and end edges to visually indicate more slides beyond the viewport.
          * @default false
         */
        "gradient"?: boolean;
        /**
          * Sets the heading text displayed above the carousel. Also used as the accessible label when no `aria` prop is set.
         */
        "heading"?: string;
        /**
          * Sets the font size of the carousel heading.
          * @default 'x-large'
         */
        "headingSize"?: CarouselHeadingSize;
        /**
          * Overrides the default label strings used for the previous, next, and page indicators — useful for localization.
         */
        "intl"?: CarouselInternationalization;
        /**
          * Emitted when the carousel navigates to a new slide, with the active and previous slide indexes in the event detail.
         */
        "onUpdate"?: (event: PCarouselCustomEvent<CarouselUpdateEventDetail>) => void;
        /**
          * Shows pagination dot indicators below the carousel. Supports responsive breakpoint values.
          * @default false
         */
        "pagination"?: BreakpointCustomizable<boolean>;
        /**
          * Enables infinite looping — navigating past the last slide wraps back to the first, and vice versa.
          * @default false
         */
        "rewind"?: boolean;
        /**
          * Sets the `href` of an in-page skip link that lets keyboard users jump past the carousel slides.
         */
        "skipLinkTarget"?: string;
        /**
          * Sets how many slides are visible at once. Use `auto` to control each slide's width via CSS. Supports responsive breakpoint values.
          * @default 1
         */
        "slidesPerPage"?: BreakpointCustomizable<CarouselSlidesPerPage>;
        /**
          * Removes whitespace before the first and after the last slide when `focusOnCenterSlide` is enabled.
          * @default false
         */
        "trimSpace"?: boolean;
        /**
          * Sets the maximum width and outer spacing of the carousel, aligned to PDS grid widths.
          * @default 'basic'
         */
        "width"?: CarouselWidth;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     * @controlled {"props": ["activeIdentifier"], "event": "update"}
     * @experimental 
     */
    interface PDrilldown {
        /**
          * Sets which `p-drilldown-item` (by `identifier`) is currently expanded to show its sub-navigation level.
         */
        "activeIdentifier"?: string | undefined;
        /**
          * Sets ARIA attributes on the drilldown dialog element for improved screen reader accessibility.
         */
        "aria"?: SelectedAriaAttributes<DrilldownAriaAttribute>;
        /**
          * Emitted when the user closes the drilldown via the dismiss button, backdrop click, or Escape key. The event detail identifies which of the three was used.
         */
        "onDismiss"?: (event: PDrilldownCustomEvent<DrilldownDismissEventDetail>) => void;
        /**
          * Emitted when the active navigation level changes, with the new `activeIdentifier` in the event detail.
         */
        "onUpdate"?: (event: PDrilldownCustomEvent<DrilldownUpdateEventDetail>) => void;
        /**
          * Controls whether the drilldown navigation panel is visible.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * @experimental 
     */
    interface PDrilldownItem {
        /**
          * Private property set by the component itself.
          * @default false
         */
        "cascade"?: boolean;
        /**
          * Sets the unique identifier matched against the drilldown's `activeIdentifier` to determine if this item is shown.
         */
        "identifier"?: string;
        /**
          * Sets the text used for the back button, sticky header, and cascade button that navigates into this navigation level.
         */
        "label"?: string;
        /**
          * Private property set by the component itself.
          * @default false
         */
        "primary"?: boolean;
        /**
          * Private property set by the component itself.
          * @default false
         */
        "secondary"?: boolean;
    }
    /**
     * @experimental 
     */
    interface PDrilldownLink {
        /**
          * Visually marks the link as the currently active navigation item, e.g. the current page.
          * @default false
         */
        "active"?: boolean;
        /**
          * Sets ARIA attributes on the link for improved accessibility. Only applies when `href` is set.
         */
        "aria"?: SelectedAriaAttributes<DrilldownLinkAriaAttribute>;
        /**
          * Sets the native `download` attribute to trigger a file download. Only applies when `href` is set.
         */
        "download"?: string;
        /**
          * When set, the component renders as an anchor navigating to this URL. Otherwise, provide a slotted anchor element.
         */
        "href"?: string;
        /**
          * Sets the `rel` attribute on the link element (e.g. `noopener`). Only applies when `href` is set.
         */
        "rel"?: string;
        /**
          * Specifies where to open the linked URL (e.g. `_self`, `_blank`). Only applies when `href` is set.
          * @default '_self'
         */
        "target"?: DrilldownLinkTarget;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface PFlyout {
        /**
          * Sets ARIA attributes on the flyout dialog element for improved screen reader accessibility.
         */
        "aria"?: SelectedAriaAttributes<FlyoutAriaAttribute>;
        /**
          * Sets the backdrop style. Use `blur` when background content is irrelevant; use `shading` when users still need visual context.
          * @default 'blur'
         */
        "backdrop"?: FlyoutBackdrop;
        /**
          * Sets the background color of the flyout panel (`canvas` or `surface`).
          * @default 'canvas'
         */
        "background"?: FlyoutBackground;
        /**
          * When enabled, clicking the backdrop will not close the flyout.
          * @default false
         */
        "disableBackdropClick"?: boolean;
        /**
          * Controls footer behavior. `fixed` keeps it anchored at the bottom; `sticky` pins it only when content overflows.
          * @default 'sticky'
         */
        "footerBehavior"?: FlyoutFooterBehavior;
        /**
          * If true the flyout stretches to the full viewport width with squared corners. Useful for smaller viewports where the flyout would otherwise fill the screen but still show rounded corners.
          * @default false
         */
        "fullscreen"?: BreakpointCustomizable<boolean>;
        /**
          * Emitted when the user closes the flyout via the dismiss button, backdrop click, or Escape key. The event detail identifies which of the three was used.
         */
        "onDismiss"?: (event: PFlyoutCustomEvent<FlyoutDismissEventDetail>) => void;
        /**
          * Emitted after the flyout's close transition completes and the panel is fully hidden.
         */
        "onMotionHiddenEnd"?: (event: PFlyoutCustomEvent<FlyoutMotionHiddenEndEventDetail>) => void;
        /**
          * Emitted after the flyout's open transition completes and the panel is fully visible.
         */
        "onMotionVisibleEnd"?: (event: PFlyoutCustomEvent<FlyoutMotionVisibleEndEventDetail>) => void;
        /**
          * Controls whether the flyout panel is visible.
          * @default false
         */
        "open"?: boolean;
        /**
          * Sets the side the flyout slides in from — `start` for left or `end` for right in LTR layouts.
          * @default 'end'
         */
        "position"?: FlyoutPosition;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface PModal {
        /**
          * Sets ARIA attributes on the dialog element for improved accessibility when no visible heading is present.
         */
        "aria"?: SelectedAriaAttributes<ModalAriaAttribute>;
        /**
          * Sets the backdrop style. Use `blur` when the modal is opened by user interaction; use `shading` when opened automatically (e.g. Cookie Consent).
          * @default 'blur'
         */
        "backdrop"?: ModalBackdrop;
        /**
          * Sets the background color of the modal panel (`canvas` or `surface`).
          * @default 'canvas'
         */
        "background"?: ModalBackground;
        /**
          * When enabled, clicking the backdrop will not close the modal.
          * @default false
         */
        "disableBackdropClick"?: boolean;
        /**
          * Shows a dismiss button in the modal header so the user can manually close it.
          * @default true
         */
        "dismissButton"?: boolean;
        /**
          * Expands the modal to the full viewport size, intended for mobile use cases. Supports responsive breakpoint values.
          * @default false
         */
        "fullscreen"?: BreakpointCustomizable<boolean>;
        /**
          * Emitted when the user closes the modal via the dismiss button, backdrop click, or Escape key. The event detail identifies which of the three was used.
         */
        "onDismiss"?: (event: PModalCustomEvent<ModalDismissEventDetail>) => void;
        /**
          * Emitted after the modal's close transition completes and the dialog is fully hidden.
         */
        "onMotionHiddenEnd"?: (event: PModalCustomEvent<ModalMotionHiddenEndEventDetail>) => void;
        /**
          * Emitted after the modal's open transition completes and the dialog is fully visible.
         */
        "onMotionVisibleEnd"?: (event: PModalCustomEvent<ModalMotionVisibleEndEventDetail>) => void;
        /**
          * Controls whether the modal dialog is visible.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * @controlled {"props": ["open"], "event": "dismiss"}
     */
    interface PSheet {
        /**
          * Sets ARIA attributes on the sheet dialog element for improved accessibility when the default `aria-label` is insufficient.
         */
        "aria"?: SelectedAriaAttributes<SheetAriaAttribute>;
        /**
          * Sets the background color of the sheet panel (`canvas` or `surface`).
          * @default 'canvas'
         */
        "background"?: SheetBackground;
        /**
          * When enabled, clicking the backdrop will not close the sheet.
          * @default false
         */
        "disableBackdropClick"?: boolean;
        /**
          * Shows a dismiss button in the sheet header so users can manually close it.
          * @default true
         */
        "dismissButton"?: boolean;
        /**
          * Emitted when the user closes the sheet via the dismiss button, backdrop click, or Escape key. The event detail identifies which of the three was used.
         */
        "onDismiss"?: (event: PSheetCustomEvent<SheetDismissEventDetail>) => void;
        /**
          * Emitted after the sheet's close transition has fully completed and the panel is hidden.
         */
        "onMotionHiddenEnd"?: (event: PSheetCustomEvent<SheetMotionHiddenEndEventDetail>) => void;
        /**
          * Emitted after the sheet's open transition has fully completed and the panel is visible.
         */
        "onMotionVisibleEnd"?: (event: PSheetCustomEvent<SheetMotionVisibleEndEventDetail>) => void;
        /**
          * Controls whether the sheet panel slides in from the bottom and is visible to the user.
          * @default false
         */
        "open"?: boolean;
    }
    interface PTableBody {
    }
    interface PTableCell {
        /**
          * Allows slotted text to wrap onto multiple lines instead of being forced onto a single line.
          * @default false
         */
        "multiline"?: boolean;
    }
    interface PTableHeadCell {
        /**
          * Hides the visible column label while keeping it accessible to screen readers. Only applies when `sort` is not set.
          * @default false
         */
        "hideLabel"?: boolean;
        /**
          * Allows the column header text to wrap onto multiple lines instead of being truncated to a single line.
          * @default false
         */
        "multiline"?: boolean;
        /**
          * Configures sorting behavior for this column by providing an `id`, `active` state, and current `direction` (`asc` or `desc`).
         */
        "sort"?: TableHeadCellSort;
    }
    interface PTableRow {
    }
    interface PToast {
    }
    interface PToastItem {
        /**
          * Emitted when the user clicks the close button on the toast item, signalling that it should be dismissed.
         */
        "onDismiss"?: (event: PToastItemCustomEvent<void>) => void;
        /**
          * Sets the visual and semantic state of the toast item, controlling its icon and color scheme (`info`, `warning`, `error`, `success`).
          * @default 'info'
         */
        "state"?: ToastState;
        /**
          * Sets the notification message text displayed inside the toast item to inform the user about the outcome of an action.
          * @default ''
         */
        "text"?: string;
    }

    interface PCanvasAttributes {
        "sidebarStartOpen": boolean;
        "sidebarEndOpen": boolean;
        "background": CanvasBackground;
    }
    interface PCarouselAttributes {
        "heading": string;
        "headingSize": CarouselHeadingSize;
        "description": string;
        "alignHeader": CarouselAlignHeader;
        "alignControls": CarouselAlignControls;
        "rewind": boolean;
        "width": CarouselWidth;
        "slidesPerPage": string;
        "pagination": string;
        "aria": SelectedAriaAttributes<CarouselAriaAttribute>;
        "intl": CarouselInternationalization;
        "activeSlideIndex": number;
        "skipLinkTarget": string;
        "focusOnCenterSlide": boolean;
        "gradient": boolean;
        "trimSpace": boolean;
    }
    interface PDrilldownAttributes {
        "open": boolean;
        "activeIdentifier": string | undefined;
        "aria": SelectedAriaAttributes<DrilldownAriaAttribute>;
    }
    interface PDrilldownItemAttributes {
        "label": string;
        "identifier": string;
        "primary": boolean;
        "secondary": boolean;
        "cascade": boolean;
    }
    interface PDrilldownLinkAttributes {
        "href": string;
        "active": boolean;
        "target": DrilldownLinkTarget;
        "download": string;
        "rel": string;
        "aria": SelectedAriaAttributes<DrilldownLinkAriaAttribute>;
    }
    interface PFlyoutAttributes {
        "open": boolean;
        "position": FlyoutPosition;
        "disableBackdropClick": boolean;
        "background": FlyoutBackground;
        "backdrop": FlyoutBackdrop;
        "footerBehavior": FlyoutFooterBehavior;
        "fullscreen": string;
        "aria": SelectedAriaAttributes<FlyoutAriaAttribute>;
    }
    interface PModalAttributes {
        "open": boolean;
        "dismissButton": boolean;
        "disableBackdropClick": boolean;
        "backdrop": ModalBackdrop;
        "background": ModalBackground;
        "fullscreen": string;
        "aria": SelectedAriaAttributes<ModalAriaAttribute>;
    }
    interface PSheetAttributes {
        "open": boolean;
        "dismissButton": boolean;
        "disableBackdropClick": boolean;
        "background": SheetBackground;
        "aria": SelectedAriaAttributes<SheetAriaAttribute>;
    }
    interface PTableCellAttributes {
        "multiline": boolean;
    }
    interface PTableHeadCellAttributes {
        "hideLabel": boolean;
        "multiline": boolean;
    }
    interface PToastItemAttributes {
        "text": string;
        "state": ToastState;
    }

    interface IntrinsicElements {
        "p-canvas": Omit<PCanvas, keyof PCanvasAttributes> & { [K in keyof PCanvas & keyof PCanvasAttributes]?: PCanvas[K] } & { [K in keyof PCanvas & keyof PCanvasAttributes as `attr:${K}`]?: PCanvasAttributes[K] } & { [K in keyof PCanvas & keyof PCanvasAttributes as `prop:${K}`]?: PCanvas[K] };
        "p-carousel": Omit<PCarousel, keyof PCarouselAttributes> & { [K in keyof PCarousel & keyof PCarouselAttributes]?: PCarousel[K] } & { [K in keyof PCarousel & keyof PCarouselAttributes as `attr:${K}`]?: PCarouselAttributes[K] } & { [K in keyof PCarousel & keyof PCarouselAttributes as `prop:${K}`]?: PCarousel[K] };
        "p-drilldown": Omit<PDrilldown, keyof PDrilldownAttributes> & { [K in keyof PDrilldown & keyof PDrilldownAttributes]?: PDrilldown[K] } & { [K in keyof PDrilldown & keyof PDrilldownAttributes as `attr:${K}`]?: PDrilldownAttributes[K] } & { [K in keyof PDrilldown & keyof PDrilldownAttributes as `prop:${K}`]?: PDrilldown[K] };
        "p-drilldown-item": Omit<PDrilldownItem, keyof PDrilldownItemAttributes> & { [K in keyof PDrilldownItem & keyof PDrilldownItemAttributes]?: PDrilldownItem[K] } & { [K in keyof PDrilldownItem & keyof PDrilldownItemAttributes as `attr:${K}`]?: PDrilldownItemAttributes[K] } & { [K in keyof PDrilldownItem & keyof PDrilldownItemAttributes as `prop:${K}`]?: PDrilldownItem[K] };
        "p-drilldown-link": Omit<PDrilldownLink, keyof PDrilldownLinkAttributes> & { [K in keyof PDrilldownLink & keyof PDrilldownLinkAttributes]?: PDrilldownLink[K] } & { [K in keyof PDrilldownLink & keyof PDrilldownLinkAttributes as `attr:${K}`]?: PDrilldownLinkAttributes[K] } & { [K in keyof PDrilldownLink & keyof PDrilldownLinkAttributes as `prop:${K}`]?: PDrilldownLink[K] };
        "p-flyout": Omit<PFlyout, keyof PFlyoutAttributes> & { [K in keyof PFlyout & keyof PFlyoutAttributes]?: PFlyout[K] } & { [K in keyof PFlyout & keyof PFlyoutAttributes as `attr:${K}`]?: PFlyoutAttributes[K] } & { [K in keyof PFlyout & keyof PFlyoutAttributes as `prop:${K}`]?: PFlyout[K] };
        "p-modal": Omit<PModal, keyof PModalAttributes> & { [K in keyof PModal & keyof PModalAttributes]?: PModal[K] } & { [K in keyof PModal & keyof PModalAttributes as `attr:${K}`]?: PModalAttributes[K] } & { [K in keyof PModal & keyof PModalAttributes as `prop:${K}`]?: PModal[K] };
        "p-sheet": Omit<PSheet, keyof PSheetAttributes> & { [K in keyof PSheet & keyof PSheetAttributes]?: PSheet[K] } & { [K in keyof PSheet & keyof PSheetAttributes as `attr:${K}`]?: PSheetAttributes[K] } & { [K in keyof PSheet & keyof PSheetAttributes as `prop:${K}`]?: PSheet[K] };
        "p-table-body": PTableBody;
        "p-table-cell": Omit<PTableCell, keyof PTableCellAttributes> & { [K in keyof PTableCell & keyof PTableCellAttributes]?: PTableCell[K] } & { [K in keyof PTableCell & keyof PTableCellAttributes as `attr:${K}`]?: PTableCellAttributes[K] } & { [K in keyof PTableCell & keyof PTableCellAttributes as `prop:${K}`]?: PTableCell[K] };
        "p-table-head-cell": Omit<PTableHeadCell, keyof PTableHeadCellAttributes> & { [K in keyof PTableHeadCell & keyof PTableHeadCellAttributes]?: PTableHeadCell[K] } & { [K in keyof PTableHeadCell & keyof PTableHeadCellAttributes as `attr:${K}`]?: PTableHeadCellAttributes[K] } & { [K in keyof PTableHeadCell & keyof PTableHeadCellAttributes as `prop:${K}`]?: PTableHeadCell[K] };
        "p-table-row": PTableRow;
        "p-toast": PToast;
        "p-toast-item": Omit<PToastItem, keyof PToastItemAttributes> & { [K in keyof PToastItem & keyof PToastItemAttributes]?: PToastItem[K] } & { [K in keyof PToastItem & keyof PToastItemAttributes as `attr:${K}`]?: PToastItemAttributes[K] } & { [K in keyof PToastItem & keyof PToastItemAttributes as `prop:${K}`]?: PToastItem[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @experimental 
             */
            "p-canvas": LocalJSX.IntrinsicElements["p-canvas"] & JSXBase.HTMLAttributes<HTMLPCanvasElement>;
            /**
             * @controlled { "props": ["activeSlideIndex"], "event": "update", "isInternallyMutated": true }
             */
            "p-carousel": LocalJSX.IntrinsicElements["p-carousel"] & JSXBase.HTMLAttributes<HTMLPCarouselElement>;
            /**
             * @controlled {"props": ["open"], "event": "dismiss"}
             * @controlled {"props": ["activeIdentifier"], "event": "update"}
             * @experimental 
             */
            "p-drilldown": LocalJSX.IntrinsicElements["p-drilldown"] & JSXBase.HTMLAttributes<HTMLPDrilldownElement>;
            /**
             * @experimental 
             */
            "p-drilldown-item": LocalJSX.IntrinsicElements["p-drilldown-item"] & JSXBase.HTMLAttributes<HTMLPDrilldownItemElement>;
            /**
             * @experimental 
             */
            "p-drilldown-link": LocalJSX.IntrinsicElements["p-drilldown-link"] & JSXBase.HTMLAttributes<HTMLPDrilldownLinkElement>;
            /**
             * @controlled {"props": ["open"], "event": "dismiss"}
             */
            "p-flyout": LocalJSX.IntrinsicElements["p-flyout"] & JSXBase.HTMLAttributes<HTMLPFlyoutElement>;
            /**
             * @controlled {"props": ["open"], "event": "dismiss"}
             */
            "p-modal": LocalJSX.IntrinsicElements["p-modal"] & JSXBase.HTMLAttributes<HTMLPModalElement>;
            /**
             * @controlled {"props": ["open"], "event": "dismiss"}
             */
            "p-sheet": LocalJSX.IntrinsicElements["p-sheet"] & JSXBase.HTMLAttributes<HTMLPSheetElement>;
            "p-table-body": LocalJSX.IntrinsicElements["p-table-body"] & JSXBase.HTMLAttributes<HTMLPTableBodyElement>;
            "p-table-cell": LocalJSX.IntrinsicElements["p-table-cell"] & JSXBase.HTMLAttributes<HTMLPTableCellElement>;
            "p-table-head-cell": LocalJSX.IntrinsicElements["p-table-head-cell"] & JSXBase.HTMLAttributes<HTMLPTableHeadCellElement>;
            "p-table-row": LocalJSX.IntrinsicElements["p-table-row"] & JSXBase.HTMLAttributes<HTMLPTableRowElement>;
            "p-toast": LocalJSX.IntrinsicElements["p-toast"] & JSXBase.HTMLAttributes<HTMLPToastElement>;
            "p-toast-item": LocalJSX.IntrinsicElements["p-toast-item"] & JSXBase.HTMLAttributes<HTMLPToastItemElement>;
        }
    }
}
